title: Guess the flag
hero_image: images/banner.png
description: How good is your flag knowledge? Create a flag quiz game—click the right flag to score points
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 # possible values: 1, 2 or 3
listed: false
ingredient: false
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: "games"
technologies: "scratch"
site_areas:
steps:
  - title: Introduction
  - title: What you will need
  - title: Draw the flags
  - title: Create a list of flags
  - title: Choose random flags
  - title: Choose a correct answer
  - title: Show the flags
  - title: Ask the question
  - title: Check the answer
  - title: Add a score
  - title: Start a new round
  - title: "Challenge: Improve the game"
